version: "3"
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: your_root_password
            MYSQL_DATABASE: your_database_name
        ports:
            - "3306:3306"

    nodejs-app:
        build: .
        ports:
            - "9001:9001"
        environment:
            MYSQL_HOST: db
            MYSQL_PORT: 3306
            MYSQL_USER: root
            MYSQL_PASSWORD: ENV DATABASE_PASSWORD
            MYSQL_DATABASE: your_database_name
        depends_on:
            - db
